### ISSUE TITLE
Set of all cases

### ISSUE THREAD

**Issue by fanf** [LPTK/Boilerless#3]
One sometimes need to get the set of all cases, for example to map it / order / etc. 

For example, Sealerate (https://github.com/mrvisser/sealerate) allows that in standard hierarchies definition. 
It seems that the proposed PR also allows it: https://github.com/scala/scala/pull/5352

As a side note, as it seems that there is a regain of interest in nice syntax for ADT, isn't it time to work on a SIP?

**Comment by LPTK** [comment]
Well, Sealerate provides exactly what you're asking for, so just use it ;-)

``` scala
object SealerateTest extends App {
  import boilerless._
  import ca.mrvisser.sealerate

  @enum class Switch  {
    object On
    object Off
  }

  def values: Set[Switch] = sealerate.values[Switch]
  println(values)  // prints: Set(On, Off)
}
```

As a sidenote, [enumeratum](https://github.com/lloydmeta/enumeratum) provides the same functionality, and I added an `@enumeratum` macro just to make the syntax nicer, so you can also do:

``` scala
  @enumeratum class Switch  {
    object On
    object Off
  }
  println(Switch.values)  // prints: Vector(On, Off)
```
